### Problem 1: Matrix Product Calculation by Hand

Given matrices: 

A = 

       [-1  2  3]               
       [4  -5  6]               
       [7   8 -9]              
       
B=       
       
       [0  2  1]
       [0  2 -8]
       [2  9 -1]
       
To find the product C = A * B, we need to calculate each element c_ij of the resulting matrix C 
       

#### Calculation of \( C \):

- For \( c_{ii} ):
\[ c_{ii} = [ 0 + 0 + 6 = 6 \]

- For \( c_{ij} \):
\[ c_{ij} = [-2 + 4 + 27 = 29 \]

- For \( c_{ik} \):
\[ c_{ik} = [-1 - 16 - 3 = -20 \]

- For \( c_{ji} \):
\[ c_{ji} [0 + 0 + 12 = 12 \]

- For \( c_{jj} \):
\[ c_{jj} [8 - 10 + 54 = 52 \]

- For \( c_{jk} \):
\[ c_{jk} [4 + 40 - 6 = 38 \]

- For \( c_{ki} \):
\[ c_{ki} [0 + 0 - 18 = -18 \]

- For \( c_{kj} \):
\[ c_{kj} [14 + 16 - 81 = -51 \]

- For \( c_{kk} \):
\[ c_{kk} [7 - 64 + 9 = -48 \]

So, the resulting matrix \( C \) is:
\[ C = \begin{pmatrix} 0 + 0 + 6 & -2 + 4 + 27 & -1-16-3 \\ 0+0+12 & 8-10+54 & 4+40-6 \\ 0+0-18 & 14+16-81 & 7-64+9 \end{pmatrix} \]



C = \begin{pmatrix} 6 & 29 & -20 \\ 12 & 52 & 38 \\ -18 & -51 & -48 \end{pmatrix}


### Problem 2: Calculation by NumPy function

In [8]:
import numpy as np

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

# Using np.matmul()
c_ndarray_matmul = np.matmul(a_ndarray, b_ndarray)

c_ndarray_matmul

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [9]:
# Using np.dot()
c_ndarray_dot = np.dot(a_ndarray, b_ndarray)

c_ndarray_dot

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [10]:
# Using @ operator
c_ndarray_at = a_ndarray @ b_ndarray

c_ndarray_at


array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

### Problem 3: Implementation of Calculation of a Certain Element

In [2]:
a = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

def calculate_element(a, b, row, col):
    element = 0
    for k in range(len(a[0])):
        element += a[row][k] * b[k][col]
    return element

calculate_element(a, b, 0, 0)


6

### Problem 4: Creating a Function that Performs Matrix Multiplication

In [3]:
def matrix_multiplication(a, b):
    rows_a, cols_a = a.shape
    rows_b, cols_b = b.shape
    if cols_a != rows_b:
        raise ValueError("The number of columns in A must be equal to the number of rows in B")
    result = np.zeros((rows_a, cols_b))
    for i in range(rows_a):
        for j in range(cols_b):
            result[i, j] = calculate_element(a, b, i, j)
    return result

matrix_multiplication(a, b)


array([[  6.,  29., -20.],
       [ 12.,  52.,  38.],
       [-18., -51., -48.]])

### Problem 5: Judge the Input Whose Calculation is Not Defined

In [4]:
def matrix_multiplication_safe(a, b):
    rows_a, cols_a = a.shape
    rows_b, cols_b = b.shape
    if cols_a != rows_b:
        print("Error: The number of columns in A must be equal to the number of rows in B")
        return None
    return matrix_multiplication(a, b)

d = np.array([[-1, 2, 3], [4, -5, 6]])
e = np.array([[-9, 8, 7], [6, -5, 4]])

matrix_multiplication_safe(d, e)


Error: The number of columns in A must be equal to the number of rows in B


### Problem 6: Transposition

In [5]:
a_T = a.T
b_T = b.T

result_T = np.matmul(a_T, b_T)
result_T_T = result_T.T  # Transpose back to original form

result_T, result_T_T


(array([[ 15, -48,  27],
        [ -2, -74, -49],
        [  3,  84,  69]]),
 array([[ 15,  -2,   3],
        [-48, -74,  84],
        [ 27, -49,  69]]))